// 短链生成服务

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: shorturl_generation_service.proto

package shorturl_generation_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortURLGenerationService_GenerateShortURL_FullMethodName = "/server.ShortURLGenerationService/GenerateShortURL"
)

// ShortURLGenerationServiceClient is the client API for ShortURLGenerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortURLGenerationServiceClient interface {
	GenerateShortURL(ctx context.Context, in *GenerateShortURLRequest, opts ...grpc.CallOption) (*GenerateShortURLResponse, error)
}

type shortURLGenerationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortURLGenerationServiceClient(cc grpc.ClientConnInterface) ShortURLGenerationServiceClient {
	return &shortURLGenerationServiceClient{cc}
}

func (c *shortURLGenerationServiceClient) GenerateShortURL(ctx context.Context, in *GenerateShortURLRequest, opts ...grpc.CallOption) (*GenerateShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateShortURLResponse)
	err := c.cc.Invoke(ctx, ShortURLGenerationService_GenerateShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortURLGenerationServiceServer is the server API for ShortURLGenerationService service.
// All implementations must embed UnimplementedShortURLGenerationServiceServer
// for forward compatibility.
type ShortURLGenerationServiceServer interface {
	GenerateShortURL(context.Context, *GenerateShortURLRequest) (*GenerateShortURLResponse, error)
	mustEmbedUnimplementedShortURLGenerationServiceServer()
}

// UnimplementedShortURLGenerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortURLGenerationServiceServer struct{}

func (UnimplementedShortURLGenerationServiceServer) GenerateShortURL(context.Context, *GenerateShortURLRequest) (*GenerateShortURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShortURL not implemented")
}
func (UnimplementedShortURLGenerationServiceServer) mustEmbedUnimplementedShortURLGenerationServiceServer() {
}
func (UnimplementedShortURLGenerationServiceServer) testEmbeddedByValue() {}

// UnsafeShortURLGenerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortURLGenerationServiceServer will
// result in compilation errors.
type UnsafeShortURLGenerationServiceServer interface {
	mustEmbedUnimplementedShortURLGenerationServiceServer()
}

func RegisterShortURLGenerationServiceServer(s grpc.ServiceRegistrar, srv ShortURLGenerationServiceServer) {
	// If the following call pancis, it indicates UnimplementedShortURLGenerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortURLGenerationService_ServiceDesc, srv)
}

func _ShortURLGenerationService_GenerateShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortURLGenerationServiceServer).GenerateShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortURLGenerationService_GenerateShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortURLGenerationServiceServer).GenerateShortURL(ctx, req.(*GenerateShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortURLGenerationService_ServiceDesc is the grpc.ServiceDesc for ShortURLGenerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortURLGenerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.ShortURLGenerationService",
	HandlerType: (*ShortURLGenerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateShortURL",
			Handler:    _ShortURLGenerationService_GenerateShortURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shorturl_generation_service.proto",
}
