// 短链生成服务

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: shorturl_generation_service.proto

package shorturl_generation_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // 原始长链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateShortURLRequest) Reset() {
	*x = GenerateShortURLRequest{}
	mi := &file_shorturl_generation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShortURLRequest) ProtoMessage() {}

func (x *GenerateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_generation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShortURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_generation_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateShortURLRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GenerateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"` // 生成的短链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateShortURLResponse) Reset() {
	*x = GenerateShortURLResponse{}
	mi := &file_shorturl_generation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShortURLResponse) ProtoMessage() {}

func (x *GenerateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_generation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShortURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_generation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_shorturl_generation_service_proto protoreflect.FileDescriptor

const file_shorturl_generation_service_proto_rawDesc = "" +
	"\n" +
	"!shorturl_generation_service.proto\x12\x06server\"<\n" +
	"\x17GenerateShortURLRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"7\n" +
	"\x18GenerateShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl2r\n" +
	"\x19ShortURLGenerationService\x12U\n" +
	"\x10GenerateShortURL\x12\x1f.server.GenerateShortURLRequest\x1a .server.GenerateShortURLResponseB\x1fZ\x1d.;shorturl_generation_serviceb\x06proto3"

var (
	file_shorturl_generation_service_proto_rawDescOnce sync.Once
	file_shorturl_generation_service_proto_rawDescData []byte
)

func file_shorturl_generation_service_proto_rawDescGZIP() []byte {
	file_shorturl_generation_service_proto_rawDescOnce.Do(func() {
		file_shorturl_generation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturl_generation_service_proto_rawDesc), len(file_shorturl_generation_service_proto_rawDesc)))
	})
	return file_shorturl_generation_service_proto_rawDescData
}

var file_shorturl_generation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shorturl_generation_service_proto_goTypes = []any{
	(*GenerateShortURLRequest)(nil),  // 0: server.GenerateShortURLRequest
	(*GenerateShortURLResponse)(nil), // 1: server.GenerateShortURLResponse
}
var file_shorturl_generation_service_proto_depIdxs = []int32{
	0, // 0: server.ShortURLGenerationService.GenerateShortURL:input_type -> server.GenerateShortURLRequest
	1, // 1: server.ShortURLGenerationService.GenerateShortURL:output_type -> server.GenerateShortURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorturl_generation_service_proto_init() }
func file_shorturl_generation_service_proto_init() {
	if File_shorturl_generation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturl_generation_service_proto_rawDesc), len(file_shorturl_generation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturl_generation_service_proto_goTypes,
		DependencyIndexes: file_shorturl_generation_service_proto_depIdxs,
		MessageInfos:      file_shorturl_generation_service_proto_msgTypes,
	}.Build()
	File_shorturl_generation_service_proto = out.File
	file_shorturl_generation_service_proto_goTypes = nil
	file_shorturl_generation_service_proto_depIdxs = nil
}
